export interface Brand {
  id: string;
  name: string;
  slug: string;
  category: string;
  description: string;
  priceRange: {
    min: number;
    max: number;
    currency: string;
  };
  logo: string;
  heroImage: string;
  lifestyleImages: string[];
  productImages: string[];
  socialMedia: {
    instagram?: string;
    facebook?: string;
    website?: string;
  };
  location: string;
  founded: number;
  specialties: string[];
  featured: boolean;
}

export const categories = [
  { id: 'all', name: 'All Brands' },
  { id: 'fashion', name: 'Fashion & Apparel' },
  { id: 'food', name: 'Food & Beverage' },
  { id: 'beauty', name: 'Beauty & Wellness' },
  // { id: 'home', name: 'Home & Living' },
  { id: 'supplements', name: 'Supplements & Nutrition' },
  { id: 'personal-care', name: 'Personal Care' },
];

export const mockBrands: Brand[] = [
  {
    id: '21',
    name: 'ULA Skin',
    slug: 'ula-skin',
    category: 'beauty',
    description: 'ULA Skin is a proudly South African skincare brand offering a range of natural, dermatologically tested products utilizing Hypochlorous Acid (HOCl) as a key ingredient. Made locally by Blulyte, an ISO 9001 certified company, ULA Skin provides effective and gentle skincare solutions that rejuvenate the skin, leaving it refreshed, smooth, and clear of blemishes, redness, and inflammation. All products are eco-friendly, vegan, cruelty-free, and approved by CANSA and AFSA.',
    priceRange: {
      min: 150,
      max: 500,
      currency: 'ZAR',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1766177540/ula_logo_lmbvwv.jpg',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1766179047/ula_lifestyle_4_a6fjmb.webp',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1766176732/ula_lifestyle_2_wp9wvv.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1766176728/ula_lifestyle_1_qipf2g.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1768726836/ula_lifestyle_5_vbdidx.avif',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1766176728/ula_product_2_tafrfb.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1766176728/ula_product_1_zbbnxn.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1766177812/ula_product_3_kej8to.webp',
    ],
    socialMedia: {
      instagram: 'ula.skincare',
      facebook: 'Ula-Skin-109415781659747',
      website: 'ulaskin.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2021,
    specialties: ['HOCl Skincare', 'Natural Ingredients', 'Eco-Conscious'],
    featured: true,
  },
  {
    id: '5',
    name: 'Hairlicious by N',
    slug: 'hairlicious-by-n',
    category: 'beauty',
    description: 'Hair’licious By N is a luxury South African hair-care brand founded from a personal journey and the belief that healthy hair starts with the scalp. Blending nature with performance, their award-winning formulations are crafted using carefully selected, high-quality ingredients to restore, strengthen, and nourish hair from root to tip. Each product is designed to deliver visible results while offering a sensorial, indulgent experience.',
    priceRange: {
      min: 115,
      max: 310,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764681522/hairlicious_logo_zran0o.jpg',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764682309/hairlicious_hero_yxawdh.jpg',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764682289/hairlicious_lifestyle_image_1_y54qqs.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764682471/hairlicious_lifestyle_image_2_naascd.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764682588/hairlicious_lifestyle_image_3_rakfwn.jpg',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764682284/hairlicious_lash_serum_sxxchy.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764681852/hairlicious_lifestyle_image_pttjv4.jpg',
    ],
    socialMedia: {
      instagram: 'hairliciousbyn',
      website: 'hairliciousbyn.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2020,
    specialties: ['Premium Skincare', 'Organic Ingredients', 'Botanical Formulations'],
    featured: true,
  },
  {
    id: '4',
    name: 'Harvest Moon Skincare',
    slug: 'harvest-moon-skincare',
    category: 'beauty',
    description: 'Harvest Moon Skin is a clean skincare brand rooted in the philosophy of "Natural Skin Conservation." It is unique for infusing all products with Baobab (the "Tree of Life") for deep hydration and combining plant-based ingredients with modern botanical stem cell technology for customized, highly-resilient skin care.',
    priceRange: {
      min: 240,
      max: 480,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764680519/harvest_moon_logo_eqhupc.jpg',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764680493/HarvestMoonCarla-CobaPhoto_79_a7zabj.jpg',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764680483/HarvestMoonCarla-CobaPhoto_61_uois0b.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764680485/HarvestMoonCarla-CobaPhoto_57_g45urm.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764679947/2_z2hgvr.jpg',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764680506/HM_Body_Set_with_Logo_ke9qnr.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764679958/6_adtpv2.png',
    ],
    socialMedia: {
      instagram: 'harvestmoonskin',
      facebook: 'harvestmoonskin',
      website: 'harvestmoonskin.com',
    },
    location: 'Nationwide, South Africa',
    founded: 2017,
    specialties: ['Baobab', 'Organic Ingredients', 'Botanical Formulations'],
    featured: false,
  },
  {
    id: '1',
    name: 'Gmaeum',
    slug: 'gmaeum',
    category: 'beauty',
    description: 'GMAEUM is a science-backed skincare brand that targets persistent concerns like acne and hyperpigmentation with transformative products. Its unique approach combines topical treatments with powerful dietary supplements (capsules) to deliver clear, lasting results from the inside out.',
    priceRange: {
      min: 199,
      max: 729,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764744029/Untitled_design_4_vseb7k.png',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764673642/gmaeum_multi_product_ifgpxf.webp',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764674063/width_640_rrjsxw.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764673642/Gmaeum_lifestyle_image_jaqnln.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764673641/gmaeum_body_scrub_lvqvqk.jpg',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764673038/gmaeum_bundle_gmooty.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764673640/purifyroot-acne-cleanser-gmaeum_grz4rp.webp',
    ],
    socialMedia: {
      instagram: 'gmaeum',
      website: 'gmaeum.com',
      facebook: 'gmaeumskincare',
    },
    location: 'Nationwide, South Africa',
    founded: 2018,
    specialties: ['Premium Skincare', 'Organic Ingredients', 'Botanical Formulations'],
    featured: true,
  },
  {
    id: '2',
    name: 'MD Glow Organics',
    slug: 'md-glow-organics',
    category: 'beauty',
    description: 'MD Glow Organics is a brand dedicated to providing organic, results-driven skincare and wellness.Its unique focus is on offering natural, targeted solutions, specializing in effective regimens for rich melanin skin, acne, and diverse skin concerns.',
    priceRange: {
      min: 99,
      max: 249,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764675696/md_glow_logo_aobfg7.jpg',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764675584/Retinol_Face_Cream_Sunscreen_Models_eyygzb.jpg',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764675517/Model_Horse_-_BFF0D349-C68D-4EC0-A46E-4CC2662444C6_a7gkr5.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764675315/multi_Product_-_2B184690-36A9-4CE9-B544-C93A2BEEEC1B_labeh5.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764675369/Collagen_Egg_Model_Hand_Tree_-_BB922CE0-F40F-48A2-92C8-BF9EF06F38C9_g7th07.jpg',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764675353/Mutli_Product_-_CAF3945A-9791-419E-AFE7-F9D66C44BE23_mkvxwx.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764675885/Turmeric_Vitamin_C_Sunscreen__BADFA99F-CC59-40C4-879F-48DEDEF34C40_kmvicf.jpg',
    ],
    socialMedia: {
      instagram: 'mdglow_organics',
      facebook: 'mdgloworganics',
      website: 'mdgloworganics.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2015,
    specialties: ['Premium Skincare', 'Organic Ingredients', 'Botanical Formulations'],
    featured: false,
  },
  //{
  //id: '3',
  //name: 'Kidz Crown',
  //slug: 'kidz-crown',
  //category: 'beauty',
  //description: 'Kidz Crown creates natural, moisture-focused haircare products exclusively for children with afro-textured hair. It is unique for specifically catering to fragile, kinky, and 4C hair types to ensure easy management and growth.',
  //priceRange: {
  //  min: 90,
  //  max: 180,
  //  currency: 'USD',
  //},
  //logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764748220/cropped-Kidz-Crown-fav-icon-1-192x192_orsdp8.png',
  //heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764677344/kidz_crown_lifestyle_image_dnqaej.jpg',
  //lifestyleImages: [
  //  'https://res.cloudinary.com/djnz3asha/image/upload/v1764677372/kidz_crown_lifestyle_image_1_lm6wcs.jpg',
  //  'https://res.cloudinary.com/djnz3asha/image/upload/v1764677728/kidx_crown_lifestyle_geg25h.jpg',
  //  'https://res.cloudinary.com/djnz3asha/image/upload/v1764678281/kidz_crown_lifestyle_image_2_jojxyj.jpg',
  //],
  //productImages: [
  //  'https://res.cloudinary.com/djnz3asha/image/upload/v1764677909/kidz_crown_bundle_kfxgtx.jpg',
  //  'https://res.cloudinary.com/djnz3asha/image/upload/v1764678034/Wash-Day-Combo-Shampoo-Conditioner-1-1024x724_fwrwkm.jpg',
  //],
  //socialMedia: {
  //  instagram: 'kidzcrown_haircare',
  //  facebook: 'kidzcrownhaircare',
  //  website: 'kidzcrown.co.za',
  //},
  //location: 'Nationwide, South Africa',
  //founded: 2019,
  //specialties: ['Organic Ingredients', 'Cruelty-Free', 'Botanical Formulations'],
  //featured: false,
  //},
  {
    id: '6',
    name: 'Activ O2',
    slug: 'activ-o2',
    category: 'beauty',
    //description for skincare
    description: 'Activ O₂ is a revolutionary skincare brand focused on clean, effective, and results-driven formulas across three ranges: Spotless, Ageless, and Brighten. Activ O₂ has the exclusive use of Activated Oxygen Technology (AOT), a potent-yet-gentle science designed to clear, brighten, and smooth skin without causing irritation.',
    priceRange: {
      min: 129,
      max: 529,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764747804/ActivO2_Favicon_Brand_01_y5pdjg.avif',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764667151/Activ_Spotless_08_1080_x_1080_15f80e1c-c23e-4ddd-9013-20f4d62c4bed_jngjhz.webp',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764667151/Activ_Spotless_08_1080_x_1080_15f80e1c-c23e-4ddd-9013-20f4d62c4bed_jngjhz.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764667150/Activ_Ageless_30_1080x1080_496a7d11-2872-4e6c-9ab1-e1d7f7859ce5_r8mtdv.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764667149/Activ_Brighten_83_1080_x_1080_2a6f539e-f53e-4f6e-86bd-9ce11c00f66d_gikyat.webp',
    ],

    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764626439/Activ_O2_Spotless_tznidl.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764667019/Activ_O2_Brighten_urov30.jpg',
    ],
    socialMedia: {
      instagram: 'getactivo2',
      facebook: 'GetActivO2',
      website: 'activo2.com',
    },
    location: 'Nationwide, South Africa',
    founded: 2016,
    //specialties for skincare
    specialties: ['Premium Skincare', 'Organic Ingredients', 'Botanical Formulations'],
    featured: false,
  },
  {
    id: '7',
    name: 'Buttercup Farmhouse',
    slug: 'buttercup-farmhouse',
    category: 'food',
    description: 'Buttercup Farmhouse is an organic beverage company specializing in  butternut coffee. With a focus on healthy, sustainable living, highlighted by its signature offering of a distinctive ground organic vegetable coffee Cucurbita Latte Bag',
    priceRange: {
      min: 60,
      max: 99,
      currency: 'USD',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764860042/buttercup_logo_lb7pz8.png',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764860436/buttercup_product_lifestyle_dtb7zh.jpg',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764860783/buttercup_product_lifestyle_2_o1kxts.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764861167/buttercup_product_lifestyle_4_xc8tde.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764861417/buttercup_farmhouse_product_lifestyle_5_edogbk.jpg',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764860436/buttercup_product_lifestyle_dtb7zh.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1764861037/buttercup_product_lifestyle_3_jldbmt.jpg',
    ],
    socialMedia: {
      instagram: 'buttercupcoffees',
      facebook: 'buttercupcoffees',
      website: 'buttercupcoffee.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2019,
    specialties: ['Organic Coffee', 'Vegetable Coffee', 'Organic Vegetable Coffee'],
    featured: false,
  },
  // {
  //   id: '8',
  //   name: 'Radiant Roots Wellness',
  //   slug: 'radiant-roots-wellness',
  //   category: 'beauty',
  //   description: 'Radiant Roots Wellness is a holistic beauty brand that bridges inner and outer wellness through nutricosmetics and topical treatments. Uniquely formulated with adaptogens, superfoods, and probiotics, the brand offers a comprehensive approach to radiant skin from within.',
  //   priceRange: {
  //     min: 175,
  //     max: 450,
  //     currency: 'USD',
  //   },
  //   logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=400&h=400&fit=crop',
  //   heroImage: 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=1200&h=800&fit=crop',
  //   lifestyleImages: [
  //     'https://images.unsplash.com/photo-1570554886111-e80fcca6a029?w=800&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1576426863848-c21f53c60b19?w=800&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&h=600&fit=crop',
  //   ],
  //   productImages: [
  //     'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=600&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600&h=600&fit=crop',
  //   ],
  //   socialMedia: {
  //     instagram: 'radiantrootswellness',
  //     website: 'radiantrootswellness.com',
  //   },
  //   location: 'Johannesburg, South Africa',
  //   founded: 2021,
  //   specialties: ['Nutricosmetics', 'Adaptogenic Skincare', 'Probiotic Formulations'],
  //   featured: false,
  // },
  // {
  //   id: '9',
  //   name: 'Velvet Touch Luxe',
  //   slug: 'velvet-touch-luxe',
  //   category: 'beauty',
  //   description: 'Velvet Touch Luxe specializes in premium body care and aromatherapy products that transform daily routines into spa-like rituals. The brand uniquely infuses each product with therapeutic-grade essential oils and rare African shea butter for unparalleled softness and sensory indulgence.',
  //   priceRange: {
  //     min: 95,
  //     max: 285,
  //     currency: 'USD',
  //   },
  //   logo: 'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?w=400&h=400&fit=crop',
  //   heroImage: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=1200&h=800&fit=crop',
  //   lifestyleImages: [
  //     'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=800&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&h=600&fit=crop',
  //   ],
  //   productImages: [
  //     'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=600&h=600&fit=crop',
  //     'https://images.unsplash.com/photo-1556228578-dd6a8f9e0e99?w=600&h=600&fit=crop',
  //   ],
  //   socialMedia: {
  //     instagram: 'velvettouchluxe',
  //     facebook: 'velvettouchluxe',
  //     website: 'velvettouchluxe.co.za',
  //   },
  //   location: 'Durban, South Africa',
  //   founded: 2018,
  //   specialties: ['Aromatherapy', 'Shea Butter Formulations', 'Luxury Body Care'],
  //   featured: false,
  // },
  {
    id: '10',
    name: 'The Herbalist',
    slug: 'the-herbalist',
    category: 'supplements',
    description: 'The Herbalist is a South African herbal supplement company that uses the latest scientific research to create natural wellness solutions. Specializing in medicinal mushroom tinctures, adaptogenic herbs, and targeted supplements, the brand uniquely combines centuries-old herbal remedies with modern science to support brain function, sleep, immunity, stress relief, and overall mental and physical health.',
    priceRange: {
      min: 99,
      max: 249,
      currency: 'ZAR',
    },
    logo: 'https://ucarecdn.com/70fd17bd-d79f-48d7-b9dd-661fe79b1d4f/-/format/auto/-/preview/480x480/-/quality/lighter/the%20herbalist%20logo.png',
    heroImage: 'https://theherbalist.co.za/cdn/shop/files/The_Herbalist_Ashwaganda_Capsules_480x480.webp?v=1742373801',
    lifestyleImages: [
      'https://theherbalist.co.za/cdn/shop/files/Lion_s_Mane_Liquid_Extract_Boost_Your_Brain_The_Herbalist_480x480.webp?v=1740572626',
      'https://theherbalist.co.za/cdn/shop/files/The_Herbalist_Moringa_Capsulse_480x480.webp?v=1742374397',
      'https://theherbalist.co.za/cdn/shop/files/The_Herbalist_Ashwaganda_Capsules_480x480.webp?v=1742373801',
    ],
    productImages: [
      'https://theherbalist.co.za/cdn/shop/files/The_Herbalist_Ashwaganda_Capsules_480x480.webp?v=1742373801',
      'https://theherbalist.co.za/cdn/shop/files/The_Herbalist_Moringa_Capsulse_480x480.webp?v=1742374397',
    ],
    socialMedia: {
      instagram: 'theherbalist.co.za',
      facebook: 'theherbalist.co.za',
      website: 'theherbalist.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2020,
    specialties: ['Medicinal Mushrooms', 'Adaptogenic Herbs', 'Science-Backed Supplements'],
    featured: false,
  },
  {
    id: '11',
    name: 'Swig',
    slug: 'swig',
    category: 'food',
    description: 'Swig is an innovative alcohol-free beverage brand offering ready-to-drink sparkling cocktails that taste as good as they look. With flavors like Blood Orange & Citrus Paloma, Passion & Vanilla Martini, Lime & Agave Margarita, and Cucumber & Ginger Sparkler, Swig provides a sophisticated alternative to alcohol for social gatherings and celebrations.',
    priceRange: {
      min: 35,
      max: 139,
      currency: 'ZAR',
    },
    logo: 'https://swig.co.za/wp-content/uploads/2024/10/cropped-swig-site-icon-192x192.png',
    heroImage: 'https://swig.co.za/wp-content/uploads/2024/09/lime-and-agave-margarita-non-alcoholic-cocktail.jpg',
    lifestyleImages: [
      'https://swig.co.za/wp-content/uploads/2024/09/cucumber-ginger-non-alcoholic-cocktail-2.jpg',
      'https://swig.co.za/wp-content/uploads/2024/09/cucumber-and-ginger-sparkler-from-swig_03.jpg',
      'https://swig.co.za/wp-content/uploads/2024/09/blood-orange-and-citrus-paloma-from-swig_04-1.jpg',
    ],
    productImages: [
      'https://swig.co.za/wp-content/uploads/2024/09/blood-orange-and-citrus-paloma-from-swig.jpg',
      'https://swig.co.za/wp-content/uploads/2024/09/passion-and-vanilla-martini-non-alcoholic-cocktail.jpg',
    ],
    socialMedia: {
      instagram: 'swig_beverages',
      website: 'swig.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2020,
    specialties: ['Alcohol-Free Cocktails', 'Sparkling Beverages', 'Premium Mixology'],
    featured: false,
  },
  {
    id: '12',
    name: 'Euphorika',
    slug: 'euphorika',
    category: 'food',
    description: 'Euphorika is Africa\'s premium alcohol-free botanical beverage made with ancient African botanicals including Sceletium Tortuosum extract, honeybush, and natural ingredients. Perfect for social gatherings as a natural social lubricant, Euphorika offers a unique taste experience that pairs well with a variety of foods while celebrating African heritage and wellness.',
    priceRange: {
      min: 40,
      max: 960,
      currency: 'ZAR',
    },
    logo: 'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/EUP_014_Foil_Icon_icon_2.png?v=1724089578',
    heroImage: 'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/bottle_tag2.png?v=1755021369',
    lifestyleImages: [
      'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/bottle_tag2.png?v=1755021369',
      'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/EUP_014_Foil_Icon_icon_2.png?v=1724089578',
      'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/bottle_tag2.png?v=1755021369',
    ],
    productImages: [
      'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/bottle_tag2.png?v=1755021369',
      'https://cdn.shopify.com/s/files/1/0647/9586/9337/files/EUP_014_Foil_Icon_icon_2.png?v=1724089578',
    ],
    socialMedia: {
      instagram: 'euphorikabeverages',
      website: 'euphorikabeverages.com',
    },
    location: 'Nationwide, South Africa',
    founded: 2019,
    specialties: ['African Botanicals', 'Alcohol-Free', 'Natural Ingredients'],
    featured: false,
  },
  {
    id: '13',
    name: 'Suki Suki Naturals',
    slug: 'suki-suki-naturals',
    category: 'beauty',
    description: 'Suki Suki Naturals offers natural haircare and skincare rooted in African heritage. The brand celebrates joyful beauty with potent formulations featuring rich African raw ingredients like Miraculous Oil and Rosehip Brightening Facial Oil. Their promise is to provide a sensory feast in personal care through deeply caring natural rituals for everyday use.',
    priceRange: {
      min: 150,
      max: 450,
      currency: 'ZAR',
    },
    logo: 'https://sukisukinaturals.com/cdn/shop/files/suki_logo_black_300dpi.png?height=100&v=1698912683',
    heroImage: 'https://sukisukinaturals.com/cdn/shop/files/U4A4728-scaled.jpg?v=1706128300&width=1100',
    lifestyleImages: [
      'https://sukisukinaturals.com/cdn/shop/files/2023-10-22--Suki-Suki-Day2_SHOT10_1005.jpg?v=1701705272&width=1100',
      'https://sukisukinaturals.com/cdn/shop/files/2023-10-21-Suki-Suki_SHOT16_2871.jpg?v=1706128300&width=1100',
      'https://sukisukinaturals.com/cdn/shop/files/2023-10-21-Suki-Suki_SHOT08_1916.jpg?v=1706863412&width=1100',
    ],
    productImages: [
      'https://sukisukinaturals.com/cdn/shop/files/U4A4719-scaled_9100c954-ddce-46b2-a376-a353eab7ccbd.jpg?v=1706128300&width=1100',
      'https://sukisukinaturals.com/cdn/shop/files/2023-10-21-Suki-Suki_SHOT17_2883.jpg?v=1706864005&width=1100',
    ],
    socialMedia: {
      instagram: 'sukisukinaturals',
      facebook: 'sukisukinaturals',
      website: 'sukisukinaturals.com',
    },
    location: 'Nationwide, South Africa',
    founded: 2018,
    specialties: ['African Heritage', 'Natural Haircare', 'Botanical Skincare'],
    featured: false,
  },
  {
    id: '14',
    name: 'Bare Ayr',
    slug: 'bare-ayr',
    category: 'supplements',
    description: 'Bare Ayr is a South African performance nutrition brand built for the Active Over 40. Offering clean, science-backed supplements including Essential Aminos, Hydrating Aminos, Pure Creatine Monohydrate, Pure Electrolytes, and Carb Fuel, Bare Ayr supports muscle strength, hydration, energy, and daily recovery. Their philosophy centers on providing the body with exactly what it needs to perform and feel its best.',
    priceRange: {
      min: 199,
      max: 599,

      currency: 'ZAR',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1764867975/Bare_Ayr_Logo_xmkpup.jpg',
    heroImage: 'https://www.bareayr.co.za/cdn/shop/files/4_5cb4a1bc-abde-4599-8b97-2f041caff63f.png?v=1763991320&width=1200',
    lifestyleImages: [
      'https://www.bareayr.co.za/cdn/shop/files/11_fba26a2c-b304-4d5f-b4d0-506eff8d8d08.png?v=1764361976&width=3840',
      'https://scontent-jnb2-1.cdninstagram.com/v/t51.82787-15/575915508_18002497643827561_3852793031934518454_n.jpg?stp=dst-jpegr_e35_tt6&_nc_cat=111&ig_cache_key=Mzc2MjcxMzUyMTU0MTYzNzE0OQ%3D%3D.3-ccb7-5&ccb=7-5&_nc_sid=58cdad&efg=eyJ2ZW5jb2RlX3RhZyI6InhwaWRzLjE0NDB4MTkyMC5oZHIuQzMifQ%3D%3D&_nc_ohc=nk65-0ztu-AQ7kNvwFEsOxu&_nc_oc=AdmqAcY-pM8O9PIrff93T-F17KecRwQ2nLeWBkkOAnFIBYlikb-2z98-hgk6o-Chy9w&_nc_ad=z-m&_nc_cid=0&_nc_zt=23&se=-1&_nc_ht=scontent-jnb2-1.cdninstagram.com&_nc_gid=d5RGFOBj3qOt9QZBW0IMrg&oh=00_Afmxt6CapOc8h4_cny9dQDXDDGQno9L1Os8miyGXmgB9Ig&oe=69379640',
      'https://www.bareayr.co.za/cdn/shop/files/gempages_537416387124003626-be68ff5e-196f-4548-a7bc-8c0e75f33aa5.png?v=1730664528&width=3840',
    ],
    productImages: [
      'https://www.bareayr.co.za/cdn/shop/files/4_5cb4a1bc-abde-4599-8b97-2f041caff63f.png?v=1763991320&width=800',
      'https://www.bareayr.co.za/cdn/shop/files/11_fba26a2c-b304-4d5f-b4d0-506eff8d8d08.png?v=1764361976&width=800',
    ],
    socialMedia: {
      instagram: 'bareayr',
      website: 'bareayr.co.za',
    },
    location: 'Nationwide, South Africa',
    founded: 2021,
    specialties: ['Performance Nutrition', 'Essential Aminos', 'Science-Backed Supplements'],
    featured: false,
  },
  // {
  //   id: '15',
  //   name: 'Velobiotics',
  //   slug: 'velobiotics',
  //   category: 'supplements',
  //   description: 'Velobiotics delivers billions more probiotics with patented microencapsulation technology, supporting gut health and overall wellness. Offering specialized probiotic formulations for women (Femina), digestive health (Velo16), weight management (GutSlim), kids (BioKid), and more, Velobiotics ensures maximum probiotic survival through stomach acid for real, science-backed results for the whole family.',
  //   priceRange: {
  //     min: 199,
  //     max: 599,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.velobiotics.co.za/cdn/shop/files/Velobiotics_640_x_640_Square_Logo.png?crop=center&height=192&v=1754223458&width=192',
  //   heroImage: 'https://www.velobiotics.co.za/cdn/shop/files/New-Hero-section-banner.jpg?v=1763450608&width=1920',
  //   lifestyleImages: [
  //     'https://www.velobiotics.co.za/cdn/shop/files/Femina-Probiotic-Caps-Supports-Womens-Health_45819608-cc58-4b73-a6d3-572a082b76cb.jpg?v=1759721508&width=1000',
  //     'https://www.velobiotics.co.za/cdn/shop/files/Velo16-Restore-Balance-in-your-gut_327f2a44-866d-4d47-97d7-bb01b62f6542.jpg?v=1751022721&width=1000',
  //     'https://www.velobiotics.co.za/cdn/shop/files/BioKid-Chewable-Tablets-Raising-Amazing-2_c35a9828-e88f-44d7-8197-261a57de2e9d.jpg?v=1751022788&width=1000',
  //   ],
  //   productImages: [
  //     'https://www.velobiotics.co.za/cdn/shop/files/FEMINA-60s.jpg?v=1751022302&width=800',
  //     'https://www.velobiotics.co.za/cdn/shop/files/VELO16-60s.jpg?v=1751022755&width=800',
  //     'https://www.velobiotics.co.za/cdn/shop/files/BIOKID-60s.jpg?v=1751022820&width=800',
  //   ],
  //   socialMedia: {
  //     instagram: 'velobiotics',
  //     facebook: 'Velobiotics',
  //     website: 'velobiotics.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2018,
  //   specialties: ['Microencapsulation Technology', 'Probiotic Supplements', 'Doctor Formulated'],
  //   featured: false,
  // },
  // {
  //   id: '16',
  //   name: 'Natchu',
  //   slug: 'natchu',
  //   category: 'beauty',
  //   description: 'Natchu is a premium African haircare brand blending time-honored natural ingredients with modern science. Gentle, effective, and safe for every texture, Natchu products nourish, protect, and restore hair health with formulations like CocoaNourish Hair Butter, Daily Dew Leave-In, and LuxeRevive Hair Elixir, celebrating Africa\'s finest ingredients elevated through innovation.',
  //   priceRange: {
  //     min: 149,
  //     max: 435,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://natchu.co.za/cdn/shop/files/Natchu_Logo_only.svg?v=1757582259&width=600',
  //   heroImage: 'https://natchu.co.za/cdn/shop/files/u2181423855_do_an_upclose_to_afro_hair_--ar_34_--v_7_3b89b177-4c05-4cc9-b76b-92214888869e.png?v=1757585831&width=1500',
  //   lifestyleImages: [
  //     'https://natchu.co.za/cdn/shop/collections/u2181423855_Create_an_image_of_a_young_attractive_elegant_bla_e1af113a-e8d8-4cb7-9c84-b1c2dc3dd8bb_0.png?v=1757501952&width=1500',
  //     'https://natchu.co.za/cdn/shop/collections/u2181423855_Using_the_look_and_feel_of_the_image_attached_cre_7c89fefd-8c6b-426e-b146-f03f632e09b1_3.png?v=1757501922&width=1500',
  //     'https://natchu.co.za/cdn/shop/collections/24-04-25NatchuProducts2000px31_4fc3c56f-0534-4e9a-addb-2b87121d26e8.jpg?v=1757586624&width=1500',
  //   ],
  //   productImages: [
  //     'https://natchu.co.za/cdn/shop/files/17-04-25NatchuProducts2000px23_faf0b51e-3c2e-4f16-ac14-264abb4437e8.jpg?v=1757496870&width=533',
  //     'https://natchu.co.za/cdn/shop/files/17-04-25NatchuProducts2000px19_96519930-0bb8-4f6b-a3e7-b3b22c05bdba.jpg?v=1757496907&width=533',
  //     'https://natchu.co.za/cdn/shop/files/24-04-25NatchuProducts2000px30_b75f1a32-ab41-40a4-8f43-59a4a76f4183.jpg?v=1757588830&width=533',
  //   ],
  //   socialMedia: {
  //     instagram: 'natchu.co.za',
  //     facebook: 'natchu.co.za',
  //     website: 'natchu.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2017,
  //   specialties: ['African Botanicals', 'Natural Haircare', 'Heritage Meets Science'],
  //   featured: false,
  // },
  // {
  //   id: '17',
  //   name: 'Saggy Stone Brewing Co.',
  //   slug: 'saggy-stone',
  //   category: 'Food & Beverages',
  //   description: 'Saggy Stone is a proudly South African craft brewery offering a range of delicious and distinctively different craft beers. With award-winning beers like Citra Nova Brut IPA, Desert Lager, Rocky River, and Bear Jam Session IPA, Saggy Stone is available fresh on tap at five taprooms throughout Cape Town and surrounding areas, or delivered to your home.',
  //   priceRange: {
  //     min: 135,
  //     max: 700,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://saggystone.co.za/cdn/shop/files/Original-Blue-Logo_200x@2x.png?v=1648500743',
  //   heroImage: 'https://saggystone.co.za/cdn/shop/files/The_Icon_Case_Four_Beers_That_Define_Saggy_Stone_1512x.jpg?v=1731588086',
  //   lifestyleImages: [
  //     'https://saggystone.co.za/cdn/shop/files/Saggy_Stone_Brewing_Co_1512x.jpg?v=1731587964',
  //     'https://saggystone.co.za/cdn/shop/files/Brewers_Small_Batch_-_Honey_Lager_1512x.jpg?v=1731588086',
  //     'https://saggystone.co.za/cdn/shop/files/EXPLORE_OUR_CORE_RANGE_BEERS_1512x.jpg?v=1731588086',
  //   ],
  //   productImages: [
  //     'https://saggystone.co.za/cdn/shop/products/Brut_IPA_Citra_Nova_300x.jpg?v=1648500743',
  //     'https://saggystone.co.za/cdn/shop/products/Rocky_River_300x.jpg?v=1648500743',
  //     'https://saggystone.co.za/cdn/shop/products/Desert_Lager_300x.jpg?v=1648500743',
  //   ],
  //   socialMedia: {
  //     instagram: 'saggystonebeer',
  //     facebook: 'saggystonebeer',
  //     website: 'saggystone.co.za',
  //   },
  //   location: 'Cape Town, South Africa',
  //   founded: 2015,
  //   specialties: ['Craft Beer', 'Award-Winning Brews', 'Taproom Experience'],
  //   featured: false,
  // },
  // {
  //   id: '18',
  //   name: 'JT35 Self-Care',
  //   slug: 'jt35-selfcare',
  //   category: 'beauty',
  //   description: 'JT35 Self-Care offers natural body odour control collection with no parabens, no sulfates, and no compromises. Specializing in intimate gel wash, buttcrack gel wash, and armpit gel wash, JT35 provides clean beauty solutions in three signature ranges: Cinnamon & Rooibos, Aloe & Cucumber, and Cocoa Butter for comprehensive personal care.',
  //   priceRange: {
  //     min: 89,
  //     max: 249,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.jt35selfcare.co.za/favicon.ico',
  //   heroImage: 'https://www.jt35selfcare.co.za/images/hero-bg.jpg',
  //   lifestyleImages: [
  //     'https://www.jt35selfcare.co.za/images/cinnamon-range.jpg',
  //     'https://www.jt35selfcare.co.za/images/cucumber-range.jpg',
  //     'https://www.jt35selfcare.co.za/images/cocoa-butter-range.jpg',
  //   ],
  //   productImages: [
  //     'https://www.jt35selfcare.co.za/images/intimate-wash-rooibos.jpg',
  //     'https://www.jt35selfcare.co.za/images/intimate-wash-aloe.jpg',
  //     'https://www.jt35selfcare.co.za/images/buttcrack-wash.jpg',
  //   ],
  //   socialMedia: {
  //     instagram: 'jt35selfcare',
  //     facebook: 'jt35selfcare',
  //     website: 'jt35selfcare.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2020,
  //   specialties: ['Natural Body Care', 'Odour Control', 'Clean Beauty'],
  //   featured: false,
  // },
  // {
  //   id: '19',
  //   name: 'Gugu Intimates',
  //   slug: 'gugu-intimates',
  //   category: 'fashion',
  //   description: 'Gugu Intimates is Africa\'s 1st skin colored underwear brand offering 5 shades of nude to match your skin tone. If you can match your makeup to your skin tone, why can\'t you match your underwear? Gugu Intimates provides T-shirt bras, strapless bras, seamless briefs, and thongs with worldwide shipping, celebrating diversity and inclusivity.',
  //   priceRange: {
  //     min: 199,
  //     max: 599,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.guguintimates.com/cdn/shop/files/Gugu_Intimates_Logo.png?height=100',
  //   heroImage: 'https://www.guguintimates.com/cdn/shop/files/hero-banner.jpg?v=1614334802&width=1500',
  //   lifestyleImages: [
  //     'https://www.guguintimates.com/cdn/shop/files/5-shades-lifestyle.jpg?v=1614334802&width=1500',
  //     'https://www.guguintimates.com/cdn/shop/files/the-new-naked-lifestyle.jpg?v=1614334802&width=1500',
  //     'https://www.guguintimates.com/cdn/shop/files/diversity-lifestyle.jpg?v=1614334802&width=1500',
  //   ],
  //   productImages: [
  //     'https://www.guguintimates.com/cdn/shop/products/tshirt-bra-product.jpg?v=1614334802&width=800',
  //     'https://www.guguintimates.com/cdn/shop/products/seamless-brief-product.jpg?v=1614334802&width=800',
  //     'https://www.guguintimates.com/cdn/shop/products/strapless-bra-product.jpg?v=1614334802&width=800',
  //   ],
  //   socialMedia: {
  //     instagram: 'guguintimates',
  //     facebook: 'guguintimates',
  //     website: 'guguintimates.com',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2016,
  //   specialties: ['Inclusive Lingerie', '5 Shades of Nude', 'Skin-Toned Underwear'],
  //   featured: false,
  // },
  // {
  //   id: '20',
  //   name: 'Kinda',
  //   slug: 'kinda',
  //   category: 'fashion',
  //   description: 'KINDA Clothing is a leading local fashion brand and designer in Cape Town, South Africa. Offering stylish collections of women\'s blouses, skirts, dresses, pants, shorts, and tops, KINDA creates clothing by women, for women. With collections like The Coco Collection, Summer Daydream, and Natural Collection, KINDA helps you find the perfect addition to your wardrobe.',
  //   priceRange: {
  //     min: 350,
  //     max: 1550,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://kinda.co.za/cdn/shop/files/landKINDAblk5_bc78d511-bca6-4e48-9ecc-830b756c650a.png?v=1614324309&width=400',
  //   heroImage: 'https://kinda.co.za/cdn/shop/files/IBP_KINDA_March2025_658.jpg?v=1749801053&width=2400',
  //   lifestyleImages: [
  //     'https://kinda.co.za/cdn/shop/files/IB_KINDA_AWCATALOGUE2024_26.jpg?v=1709280946&width=1080',
  //     'https://kinda.co.za/cdn/shop/files/IB_KINDA_AWCATALOGUE2024_9.jpg?v=1709280744&width=1080',
  //     'https://kinda.co.za/cdn/shop/collections/the-coco-collection.jpg?v=1749801053&width=1500',
  //   ],
  //   productImages: [
  //     'https://kinda.co.za/cdn/shop/products/gianna-dress-denim.jpg?v=1749801053&width=800',
  //     'https://kinda.co.za/cdn/shop/products/lizari-crossover-top.jpg?v=1749801053&width=800',
  //     'https://kinda.co.za/cdn/shop/products/dream-ruffle-bag.jpg?v=1749801053&width=800',
  //   ],
  //   socialMedia: {
  //     instagram: 'kinda.co.za',
  //     facebook: 'kindaclothing',
  //     website: 'kinda.co.za',
  //   },
  //   location: 'Cape Town, South Africa',
  //   founded: 2014,
  //   specialties: ['Women\'s Fashion', 'Local Design', 'Contemporary Clothing'],
  //   featured: false,
  // },
  // {
  //   id: '22',
  //   name: 'Gloei Beauty',
  //   slug: 'gloei-beauty',
  //   category: 'beauty',
  //   description: 'Gloei Beauty is a South African skincare brand that simplifies complex skincare routines into high-performing, effective solutions. Their signature "Gloei Glow" is achieved through products like the Brightening Serum and Hydrating Cleanser, designed for all skin types to achieve a healthy, luminous complexion.',
  //   priceRange: {
  //     min: 250,
  //     max: 800,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://gloei.beauty/cdn/shop/files/logo_for_shopify.png?v=1656164443&width=600',
  //   heroImage: 'https://gloei.beauty/cdn/shop/files/holiday_bannerr3.jpg?v=1765262478&width=3840',
  //   lifestyleImages: [
  //     'https://gloei.beauty/cdn/shop/collections/Gloei_Product_Props_Double_1_0155.jpg?v=1656402384&width=1500',
  //     'https://gloei.beauty/cdn/shop/files/flower_symbol_banner.jpg?v=1652190167&width=3840',
  //   ],
  //   productImages: [
  //     'https://gloei.beauty/cdn/shop/files/Gloei_Product_Props_Double_1_0155.jpg?v=1656402384&width=1500',
  //   ],
  //   socialMedia: {
  //     instagram: 'gloei.beauty',
  //     website: 'gloei.beauty',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2021,
  //   specialties: ['Brightening Skincare', 'High-Performance Formulas', 'Luminous Skin'],
  //   featured: true,
  // },
  // {
  //   id: '23',
  //   name: 'Rawbiotics',
  //   slug: 'rawbiotics',
  //   category: 'supplements',
  //   description: 'Rawbiotics provides live liquid probiotics that are non-freeze-dried and contain more probiotic strains than most supplements. Their formulations for Daily, Gut, and Immune health provide natural fermented probiotics for balanced gut health and overall wellness, suitable for the whole family.',
  //   priceRange: {
  //     min: 150,
  //     max: 450,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.rawbiotics.co.za/cdn/shop/files/Logo_360x_afa11f1c-7c74-4d53-b67e-ba934846e553.png?v=1707897687&width=600',
  //   heroImage: 'https://www.rawbiotics.co.za/cdn/shop/files/RAW_Web_Banners_Desktop.webp?v=1766158880&width=3840',
  //   lifestyleImages: [
  //     'https://www.rawbiotics.co.za/cdn/shop/files/RAWBIOTICS_BANNER_UPDATED-_1_-_1_6c997ef3-039d-41ab-9966-2381417f58ca.jpg?v=1695734794&width=3840',
  //     'https://www.rawbiotics.co.za/cdn/shop/files/Rawbitoics_Liquid_Probiotics.png?v=1689847547&width=3840',
  //   ],
  //   productImages: [
  //     'https://www.rawbiotics.co.za/cdn/shop/files/Rawbitoics_Liquid_Probiotics.png?v=1689847547&width=3840',
  //   ],
  //   socialMedia: {
  //     instagram: 'rawbiotics',
  //     website: 'rawbiotics.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2015,
  //   specialties: ['Live Probiotics', 'Gut Health', 'Natural Fermentation'],
  //   featured: false,
  // },
  // {
  //   id: '24',
  //   name: 'Neofresh',
  //   slug: 'neofresh',
  //   category: 'food',
  //   description: 'Neofresh is a leading South African produce brand, bringing the best of their farms directly to your table. Specializing in fresh papaya, litchis, and other seasonal fruits, Neofresh focuses on quality, sustainability, and the natural goodness of farm-fresh produce.',
  //   priceRange: {
  //     min: 30,
  //     max: 200,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://neofresh.net/wp-content/uploads/2020/06/Neofresh-Logo-1.png',
  //   heroImage: 'http://neofresh.net/wp-content/uploads/2022/03/Papaya-Neofresh-1.jpg',
  //   lifestyleImages: [
  //     'https://neofresh.net/wp-content/uploads/2023/11/Papaya-and-bacon-filled-tomatoes--700x441.jpg',
  //     'https://neofresh.net/wp-content/uploads/2023/09/IMG_8177-700x441.jpg',
  //     'https://neofresh.net/wp-content/uploads/2023/09/IMG_7994-2-700x441.jpg',
  //   ],
  //   productImages: [
  //     'http://neofresh.net/wp-content/uploads/2022/03/Papaya-Neofresh-1.jpg',
  //   ],
  //   socialMedia: {
  //     website: 'neofresh.net',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2000,
  //   specialties: ['Fresh Produce', 'Sustainable Farming', 'Premium Papaya'],
  //   featured: false,
  // },
  // {
  //   id: '25',
  //   name: 'Lumi Glo Skincare',
  //   slug: 'lumi-glo',
  //   category: 'beauty',
  //   description: 'Lumi Glo Skincare offers high-quality, vegan, and cruelty-free sheet masks and skincare essentials. Designed to give you a spa-like experience at home, their products target hydration, brightening, and clearing, using powerful ingredients for visible results and a healthy glow.',
  //   priceRange: {
  //     min: 100,
  //     max: 450,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.lumigloskin.com/cdn/shop/files/1_4.png?v=1718103587',
  //   heroImage: 'https://www.lumigloskin.com/cdn/shop/files/LUMI_GLO_AWARD_PICS_1920_x_900_px.png?v=1762434563&width=3840',
  //   lifestyleImages: [
  //     'https://www.lumigloskin.com/cdn/shop/files/Lum_Glo_Sales_2160_x_900_px_1_4f2b7336-9a01-4616-8092-ad8d054dc2fc.png?v=1728980311&width=3840',
  //     'https://www.lumigloskin.com/cdn/shop/files/Lum_Glo_Sales_2160_x_900_px_6e37c472-fd54-43d9-b81a-433fb62d6786.png?v=1764685591&width=3840',
  //   ],
  //   productImages: [
  //     'https://www.lumigloskin.com/cdn/shop/files/Lum_Glo_Sales_2160_x_900_px_2_6b222c5e-7e1b-4428-a276-e2e3c95217d4.png?v=1729253121&width=3840',
  //   ],
  //   socialMedia: {
  //     instagram: 'lumigloskin',
  //     website: 'lumigloskin.com',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2019,
  //   specialties: ['Sheet Masks', 'Vegan Skincare', 'At-Home Spa'],
  //   featured: true,
  // },
  // {
  //   id: '26',
  //   name: 'Zanna Skin',
  //   slug: 'zanna-skin',
  //   category: 'beauty',
  //   description: 'Zanna Skin specializes in the AcnePro range, providing targeted solutions for acne-prone skin. Their science-backed formulations help clear breakouts, reduce inflammation, and prevent future occurrences, focusing on skin health and confidence.',
  //   priceRange: {
  //     min: 180,
  //     max: 550,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://zannaskin.com/cdn/shop/files/ZANNA_LOGO_FA_FILES_PRIMARY_LOGO.png?crop=center&height=59&v=1724248411&width=250',
  //   heroImage: 'https://zannaskin.com/cdn/shop/files/FOAMING_WASH_HOME_PAGE_2.jpg?v=1724833196&width=3500',
  //   lifestyleImages: [
  //     'https://zannaskin.com/cdn/shop/files/FOAMING-WASH-HOME-PAGE-MOBILE.jpg?v=1724841411&width=2333',
  //     'https://zannaskin.com/cdn/shop/files/Zanna_Product2807-Edit-Edit.jpg?v=1724243147&width=2333',
  //   ],
  //   productImages: [
  //     'https://zannaskin.com/cdn/shop/files/Zanna_Product2807-Edit-Edit.jpg?v=1724243147&width=2333',
  //   ],
  //   socialMedia: {
  //     instagram: 'zannaskin',
  //     website: 'zannaskin.com',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2020,
  //   specialties: ['Acne Treatment', 'Science-Backed Skincare', 'Dermatologist Inspired'],
  //   featured: false,
  // },
  // {
  //   id: '27',
  //   name: 'Little Tlou',
  //   slug: 'little-tlou',
  //   category: 'food',
  //   description: 'Little Tlou, a range by Tlou Tea, offers South African herbal teas specifically blended for children and families. Their caffeine-free Rooibos blends are natural, healthy, and delicious, perfect for daily hydration and wellness from a young age.',
  //   priceRange: {
  //     min: 45,
  //     max: 120,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://tloutea.co.za/cdn/shop/files/Tlou_Logo-02.png?v=1666424669',
  //   heroImage: 'https://tloutea.co.za/cdn/shop/files/littletlou.png?v=1685540450&width=1500',
  //   lifestyleImages: [
  //     'https://tloutea.co.za/cdn/shop/files/SFTC._Tlou_Tea_Kids-52_1.jpg?v=1685540933&width=1500',
  //     'https://tloutea.co.za/cdn/shop/files/little1.png?v=1685543294&width=1500',
  //     'https://tloutea.co.za/cdn/shop/files/SFTC._Tlou_Tea_Kids-151_1.jpg?v=1685541363&width=1500',
  //   ],
  //   productImages: [
  //     'https://tloutea.co.za/cdn/shop/files/littletlou.png?v=1685540450&width=1500',
  //   ],
  //   socialMedia: {
  //     website: 'tloutea.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2018,
  //   specialties: ['Kids Herbal Tea', 'Caffeine-Free', 'Healthy Hydration'],
  //   featured: false,
  // },
  // {
  //   id: '28',
  //   name: 'Superlatte',
  //   slug: 'superlatte',
  //   category: 'food',
  //   description: 'Superlatte creates plant-based superfood lattes that are gluten-free, dairy-free, and full of natural goodness. From Turmeric and Beetroot to Matcha and Cacao, their blends provide a healthy, vibrant alternative to traditional coffee and tea.',
  //   priceRange: {
  //     min: 95,
  //     max: 250,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://superlatte.com/cdn/shop/files/Superlatte_Logo_Gold_b75f9040-4e2c-4f8a-a368-568c75f571a4.png?height=88&v=1756903443',
  //   heroImage: 'https://superlatte.com/cdn/shop/files/hone.png?v=1750867196&width=3840',
  //   lifestyleImages: [
  //     'https://superlatte.com/cdn/shop/files/BeetrootandCocoaSuperlatte.webp?v=1757085456&width=1946',
  //     'https://superlatte.com/cdn/shop/files/ChagaCocoaSuperlatte_c5395f1c-f7c4-41b1-807e-d999e7f80176.webp?v=1757085582&width=1946',
  //   ],
  //   productImages: [
  //     'https://superlatte.com/cdn/shop/files/DarkCocoaSuperlatte_951af380-6839-464f-8a06-103ce0111b18.webp?v=1757085556&width=1946',
  //   ],
  //   socialMedia: {
  //     instagram: 'superlatte',
  //     website: 'superlatte.com',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2016,
  //   specialties: ['Superfood Lattes', 'Plant-Based Nutrition', 'Healthy Beverages'],
  //   featured: true,
  // },
  // {
  //   id: '29',
  //   name: 'Rooted Natural',
  //   slug: 'rooted-natural',
  //   category: 'food',
  //   description: 'Rooted Natural offers healthy, plant-based frozen meals and snacks that make nutritious eating convenient. Their chef-prepared recipes focus on whole ingredients, flavor, and sustainability, perfect for busy lifestyles seeking wholesome nutrition.',
  //   priceRange: {
  //     min: 60,
  //     max: 180,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://www.rootednatural.co.za/cdn/shop/files/Asset_3_2x_c20c694a-def5-496c-86f5-ac240608eead_160x.png?v=1613563369',
  //   heroImage: 'https://www.rootednatural.co.za/cdn/shop/files/Hi_res-00011_1200x.png?v=1613563940',
  //   lifestyleImages: [
  //     'https://www.rootednatural.co.za/cdn/shop/files/dawn-fashion-love-people-4040784_3x_da6225a5-7c6a-4b56-9bd5-e246762a3aff_600x.png?v=1613563658',
  //   ],
  //   productImages: [
  //     'https://www.rootednatural.co.za/cdn/shop/products/ChickenLiver_SweetPotatoandThyme_600x.jpg?v=1614160891',
  //     'https://www.rootednatural.co.za/cdn/shop/products/RosemaryBeef_Carrot_Celery_Potato_600x.jpg?v=1614194416',
  //   ],
  //   socialMedia: {
  //     instagram: 'rooted_natural',
  //     website: 'rootednatural.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2017,
  //   specialties: ['Plant-Based Meals', 'Chef-Prepared', 'Sustainable Eating'],
  //   featured: false,
  // },
  // {
  //   id: '30',
  //   name: 'Mondvol Cookies',
  //   slug: 'mondvol-cookies',
  //   category: 'food',
  //   description: 'Mondvol Cookies provides handmade, decadent cookies delivered straight to your door across South Africa. With a focus on high-quality ingredients and traditional baking methods, they offer a range of unique flavors that provide a truly "mouthful" of happiness in every bite.',
  //   priceRange: {
  //     min: 150,
  //     max: 450,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://mondvol.co/wp-content/uploads/2025/04/logo-white-big.svg',
  //   heroImage: 'https://mondvol.co/wp-content/uploads/2025/12/Biscoff-x-Red-Velvet-4-Large.jpeg.webp',
  //   lifestyleImages: [
  //     'https://mondvol.co/wp-content/uploads/2025/03/classic-box-1024x695.png.webp',
  //     'https://mondvol.co/wp-content/uploads/2025/04/Highlight-Mondvol-Classic-Cookie-Box.jpg',
  //   ],
  //   productImages: [
  //     'https://mondvol.co/wp-content/uploads/2025/04/Subtitle-2-1024x1024.jpg.webp',
  //   ],
  //   socialMedia: {
  //     instagram: 'mondvol_cookies',
  //     website: 'mondvol.co',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2021,
  //   specialties: ['Artisanal Cookies', 'Handmade Treats', 'Gourmet Baking'],
  //   featured: false,
  // },
  // {
  //   id: '31',
  //   name: 'Sip',
  //   slug: 'sip',
  //   category: 'food',
  //   description: 'Sip is a hydration and vitamin ritual in a bottle. Their range of infused waters and vitamin-enriched drinks provides a refreshing way to stay hydrated while getting your daily dose of sunshine and essential nutrients.',
  //   priceRange: {
  //     min: 35,
  //     max: 150,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://sipsip.co.za/cdn/shop/files/PRIMARY_LOGO___NEG___FIRE.png?v=1756289234&width=600',
  //   heroImage: 'https://sipsip.co.za/cdn/shop/files/Sip_Website_Banner_2.jpg?v=1758268173&width=3840',
  //   lifestyleImages: [
  //     'https://sipsip.co.za/cdn/shop/files/SIP_250903_SHOT08_182.jpg?v=1757406170&width=1500',
  //     'https://sipsip.co.za/cdn/shop/files/Everyday_glow.jpg?v=1758276819&width=3200',
  //   ],
  //   productImages: [
  //     'https://sipsip.co.za/cdn/shop/files/Discovery_Box_8_6_Varients_White_background_150dpi.png?v=1762791422&width=1500',
  //   ],
  //   socialMedia: {
  //     instagram: 'sipsip_sa',
  //     website: 'sipsip.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2022,
  //   specialties: ['Vitamin Hydration', 'Functional Beverages', 'Natural Flavors'],
  //   featured: false,
  // },
  // {
  //   id: '32',
  //   name: 'SANRAE Wellness',
  //   slug: 'sanrae-wellness',
  //   category: 'beauty',
  //   description: 'SANRAE Wellness (formerly SANA) offers luxury self-care and wellness products designed to elevate your daily rituals. From bath salts to body oils, their products focus on holistic health, relaxation, and the power of natural ingredients for a balanced life.',
  //   priceRange: {
  //     min: 220,
  //     max: 650,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://sanraewellness.com/cdn/shop/files/Sanrae_Logo.png?v=1753772156&width=4167',
  //   heroImage: 'https://sanraewellness.com/cdn/shop/files/New_website_banners_3200x1200_5.png?v=1765976602&width=3200',
  //   lifestyleImages: [
  //     'https://sanraewellness.com/cdn/shop/files/DSC07629_copy.jpg?v=1751351365&width=2000',
  //     'https://sanraewellness.com/cdn/shop/files/pexels-gabby-k-7144904.jpg?v=1740496331&width=5472',
  //   ],
  //   productImages: [
  //     'https://sanraewellness.com/cdn/shop/files/1.png?v=1763566907&width=2048',
  //   ],
  //   socialMedia: {
  //     instagram: 'sanrae_wellness',
  //     website: 'sanraewellness.com',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2021,
  //   specialties: ['Luxury Self-Care', 'Holistic Wellness', 'Natural Body Care'],
  //   featured: false,
  // },
  // {
  //   id: '33',
  //   name: 'VitaminMe',
  //   slug: 'vitaminme',
  //   category: 'supplements',
  //   description: 'VitaminMe provides personalized vitamin subscriptions tailored to your unique health goals. Based on a quick assessment, they deliver a monthly pack of high-quality supplements to support your energy, immunity, skin, and overall wellbeing.',
  //   priceRange: {
  //     min: 199,
  //     max: 600,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://vitaminme.co.za/wp-content/uploads/2025/01/VitaminMe-Logo-V2.svg',
  //   heroImage: 'https://vitaminme.co.za/wp-content/uploads/2025/10/tegansmithphotography-80-scaled.jpg',
  //   lifestyleImages: [
  //     'https://vitaminme.co.za/wp-content/uploads/2025/10/Menu-Packs-2.png',
  //     'https://vitaminme.co.za/wp-content/uploads/2025/10/Screenshot-2025-10-15-at-13.39.29.png',
  //   ],
  //   productImages: [
  //     'https://vitaminme.co.za/wp-content/uploads/2025/10/Menu-Packs-3.png',
  //   ],
  //   socialMedia: {
  //     instagram: 'vitaminme_sa',
  //     website: 'vitaminme.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2018,
  //   specialties: ['Personalized Vitamins', 'Subscription Wellness', 'Targeted Nutrition'],
  //   featured: false,
  // },
  // {
  //   id: '34',
  //   name: 'Mrs Milk',
  //   slug: 'mrs-milk',
  //   category: 'food',
  //   description: 'Mrs Milk specializes in lactation-supporting snacks and wellness products for breastfeeding mothers. Their delicious lactation cookies and bars are designed to naturally boost milk supply while providing essential nutrients for both mom and baby.',
  //   priceRange: {
  //     min: 80,
  //     max: 350,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://d3k81ch9hvuctc.cloudfront.net/company/LZeiE7/images/00115b01-5fd3-484b-85b1-23d00256bcc7.jpeg',
  //   heroImage: 'https://mrsmilk.co.za/cdn/shop/files/Mrs_Milk_Main_Banner_Image850_1600x.png?v=1685052384',
  //   lifestyleImages: [
  //     'https://mrsmilk.co.za/cdn/shop/files/Natasha_and_Kids_Mrs_Milk1080_50x.png?v=1686299463',
  //     'https://mrsmilk.co.za/cdn/shop/files/NatashaAboutUs600_1600x.jpg?v=1691745408',
  //   ],
  //   productImages: [
  //     'https://mrsmilk.co.za/cdn/shop/files/lactation-products-classic_5000x_eecb38f8-851d-44a6-b5cd-e3374f15d6c1_50x.jpg',
  //   ],
  //   socialMedia: {
  //     instagram: 'mrsmilk_sa',
  //     website: 'mrsmilk.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2017,
  //   specialties: ['Lactation Support', 'Maternal Wellness', 'Healthy Snacking'],
  //   featured: false,
  // },
  // {
  //   id: '35',
  //   name: 'WhiskAway',
  //   slug: 'whiskaway',
  //   category: 'food',
  //   description: 'WhiskAway creates handmade, artisanal ice cream and sorbets using only the finest natural ingredients. Their unique flavor combinations and creamy textures provide a premium dessert experience that celebrates the joy of delicious treats.',
  //   priceRange: {
  //     min: 45,
  //     max: 180,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://whiskawayicecream.co.za/wp-content/uploads/2023/04/Whisk-Away_LOGO_Full-Colour.png',
  //   heroImage: 'https://whiskawayicecream.co.za/wp-content/uploads/2023/05/Bicycle-Home-Page.png',
  //   lifestyleImages: [
  //     'https://whiskawayicecream.co.za/wp-content/uploads/sb-instagram-feed-images/518892155_18518920258063830_8935864568754686880_nlow.webp',
  //     'https://whiskawayicecream.co.za/wp-content/uploads/2023/04/Ingredients.png',
  //   ],
  //   productImages: [
  //     'https://whiskawayicecream.co.za/wp-content/uploads/2023/08/WA_Website-Image_SORBETS.png',
  //   ],
  //   socialMedia: {
  //     instagram: 'whiskaway_ice_cream',
  //     website: 'whiskawayicecream.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2015,
  //   specialties: ['Artisanal Ice Cream', 'Natural Ingredients', 'Gourmet Sorbets'],
  //   featured: false,
  // },
  // {
  //   id: '36',
  //   name: 'Safepad',
  //   slug: 'safepad',
  //   category: 'personal-care',
  //   description: 'Safepad offers reusable, antimicrobial menstrual pads designed for safety, comfort, and sustainability. Their innovative technology provides lasting protection, helping to end period poverty and reduce environmental waste.',
  //   priceRange: {
  //     min: 95,
  //     max: 350,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://safepad.co.za/wp-content/uploads/elementor/thumbs/Safepad-website-logo-header-min-qcouvd9ic2po97tq2vsicydbrfu23ejpzgx35rwu80.png',
  //   heroImage: 'https://safepad.co.za/wp-content/uploads/2024/08/SafePad-Chommie-Social-Media-Elements_Facebook.png',
  //   lifestyleImages: [
  //     'https://safepad.co.za/wp-content/uploads/2022/05/Safepad-website-What-is-Safepad-photo-02-min.jpg',
  //     'https://safepad.co.za/wp-content/uploads/2022/06/Safepad-image-1-768x576.jpeg',
  //   ],
  //   productImages: [
  //     'https://safepad.co.za/wp-content/uploads/2022/11/Safepad-website-image-Safepad-4-pack-min-NEW.jpg',
  //   ],
  //   socialMedia: {
  //     website: 'safepad.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2016,
  //   specialties: ['Reusable Menstrual Pads', 'Antimicrobial Technology', 'Sustainable Healthcare'],
  //   featured: false,
  // },
  // {
  //   id: '37',
  //   name: 'Kokee',
  //   slug: 'kokee',
  //   category: 'food',
  //   description: 'Kokee provides everyday hydration solutions with a focus on style and functionality. Their premium reusable water bottles and accessories are designed to make staying hydrated easy and environmentally friendly.',
  //   priceRange: {
  //     min: 150,
  //     max: 650,
  //     currency: 'ZAR',
  //   },
  //   logo: 'https://kokee.co.za/cdn/shop/files/Untitled_design_9.png?height=48&v=1751755886',
  //   heroImage: 'https://kokee.co.za/cdn/shop/files/Morning_Fast_9.png?height=2750&v=1766074200',
  //   lifestyleImages: [
  //     'https://kokee.co.za/cdn/shop/files/kokee-lifestyle18_1.png',
  //     'https://judgeme.imgix.net/kokee/1766300649__1766300643104-img_1136__original.jpeg?auto=format&w=1024',
  //   ],
  //   productImages: [
  //     'https://kokee.co.za/cdn/shop/files/everyday-electrolyte-mix-4675355.png',
  //   ],
  //   socialMedia: {
  //     instagram: 'kokee_sa',
  //     website: 'kokee.co.za',
  //   },
  //   location: 'Nationwide, South Africa',
  //   founded: 2021,
  //   specialties: ['Reusable Bottles', 'Style Hydration', 'Eco-Friendly Accessories'],
  //   featured: false,
  // },
  {
    id: '38',
    name: 'The Mushroom Box',
    slug: 'the-mushroom-box',
    category: 'food',
    description: 'The Mushroom Box is South Africa\'s leading brand for home mushroom cultivation, making it easy for anyone to grow nutritious and delicious medicinal and gourmet mushrooms. Based in Cape Town and founded in 2019, they offer simplified grow kits for varieties like Oyster and Lion\'s Mane, alongside a range of premium mushroom tinctures and supplements. Their mission is to promote sustainable living and wellness through the magic of fungi.',
    priceRange: {
      min: 199,
      max: 350,
      currency: 'ZAR',
    },
    logo: 'https://res.cloudinary.com/djnz3asha/image/upload/v1770899198/TMB_Logo_V1_5_qh4abi.webp',
    heroImage: 'https://res.cloudinary.com/djnz3asha/image/upload/v1770899199/the_mushroom_box_product_lifestyle_5_l7fy6e.webp',
    lifestyleImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1770899199/the_mushroom_box_product_lifestyle_6_eo3k7o.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1770899816/the_mushroom_box_product_lifestyle_7_j1jqkt.webp',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1770899199/the_mushroom_box_product_lifestyle_4_zdpxh9.webp',
    ],
    productImages: [
      'https://res.cloudinary.com/djnz3asha/image/upload/v1770899199/the_mushroom_box_product_lifestyle_2_ha6ohx.jpg',
      'https://res.cloudinary.com/djnz3asha/image/upload/v1770899200/the_mushroom_box_product_lifestyle_1_h6tdje.webp',
    ],
    socialMedia: {
      instagram: 'themushroombox.shop',
      website: 'themushroombox.shop',
    },
    location: 'Cape Town, South Africa',
    founded: 2019,
    specialties: ['Home Mushroom Cultivation', 'Medicinal Mushroom Tinctures', 'Sustainable Living'],
    featured: false,
  },
];

